spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    source:
      jdbc-url: jdbc:mysql://rds8l3889yql6705lkkepublic.mysql.rds.aliyuncs.com:3306/pomp?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
      username: pmptest
      password: zkdj_yqgj2)!&
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP-source
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    target:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/pomp?characterEncoding=utf8&useSSL=false
      username: root
      password: root
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP-source
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8088
